
project:
  type: website
  output-dir: docs
  resources:
    - data/datos_con_errores.csv
    - images

website:
  title: "Análisis de la biodiversidad en R y SIG"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: "Inicio"
      - text: "Tema 1. Introducción general a R"
        menu:
          - href: Tema1-Intro1.qmd
            text: "Primera parte"
          - href: Tema1-Intro2.qmd
            text: "Segunda parte"
      - href: Tema2.qmd
        text: "Tema 2. Manejo y filtrado de datos de biodiversidad"
      - href: Tema3.qmd
        text: "Tema 3. Métodos de comparaciones"
        menu:
          - href: Tema3-1-Indices.qmd
            text: "Índices de Biodiversidad"
          - href: Tema3.qmd
            text: "Métodos de comparaciones"
      - href: Tema4.qmd
        text: "Tema 4. Representación gráfica y presentación de resultados"
  page-navigation: true
  
lang: es

# Opciones por defecto para todas las páginas con webR
webr:
  show-startup-message: false
  channel-type: post-message   # recomendado para GitHub Pages
  packages: [tidyverse, ggplot2,vegan,FD, picante]

filters:
    - webr

format:
  html:
    css: estilos.css  