
project:
  type: website
  output-dir: docs
  resources:
    - data/datos_con_errores.csv
    - images

website:
  title: "Análisis de la biodiversidad en R y SIG"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: "Inicio"
      - text: "Tema 1. Intro"
        menu:
          - href: Tema1-Intro1.qmd
            text: "Primera parte"
          - href: Tema1-Intro2.qmd
            text: "Segunda parte"
      
      - href: Tema2.qmd
        text: "Tema 2. Manejo datos"
      
      - text: "Tema 3. Índices y Métodos"
        menu:
          - href: Tema3-1-Indices.qmd
            text: "Índices de Biodiversidad"
          - href: Tema3-2-Metodos-anova.qmd
            text: "Anova"
          - href: Tema3-3-Metodos-regresion.qmd
            text: "Regresión"
          - href: Tema3-4-Metodos-ordenacion.qmd
            text: "Ordenación"
      
      - href: Tema4.qmd
        text: "Tema 4. Gráficos"
  
  page-navigation: true
  
lang: es

# Opciones por defecto para todas las páginas con webR
webr:
  show-startup-message: false
  channel-type: post-message   # recomendado para GitHub Pages
  packages: [tidyverse, ggplot2,vegan,FD, picante]

filters:
    - webr

format:
  html:
    css: estilos.css  