
project:
  type: website
  output-dir: docs

website:
  title: "Análisis de la biodiversidad en R y SIG"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: "Inicio"
      - text: "Tema 1. Introducción general a R"
        menu:
          - href: Tema1-Intro1.qmd
            text: "Primera parte"
          - href: Tema1-Intro2.qmd
            text: "Segunda parte"
      - href: Tema2.qmd
        text: "Tema 2. Manejo y filtrado de datos de biodiversidad"
      - href: Tema3.qmd
        text: "Tema 3. Métodos de comparaciones"
      - href: Tema4.qmd
        text: "Tema 4. Representación gráfica y presentación de resultados"
  page-navigation: true

lang: es

format:
  html:
    theme: cosmo
    toc: true

engine: knitr

# Opciones por defecto para todas las páginas con webR
webr:
  show-startup-message: false
  channel-type: post-message   # recomendado para GitHub Pages
  packages: [dplyr, ggplot2]
filters:
  - webr
